language: python
python:
  - "3.6"
  - "3.6-dev" # 3.6 development branch
  - "3.7-dev" # 3.7 development branch
  
# command to install dependencies
install:
  - pip install -r requirements.txt

# test command, build command
script:
  - pytest
  - pyinstaller --onefile --version-file=version.txt main.py

# Deployment code    
deploy:
  provider: releases
  api_key:
    secure: $DEPLOYMENT_KEY_GITHUB
  file:
    - "dist/main.exe"
  skip_cleanup: true
  on:
    tags: true
    TRAVIS_PYTHON_VERSION: "3.6"
    
