matrix:
  include:
   - language: python
     env: TRAVIS_PYTHON_VERSION=3.6
   - language: python
     env: TRAVIS_PYTHON_VERSION=3.6-dev # 3.6 development branch
  
# command to install dependencies
install:
  - pip install -r .travis/requirements.txt

# test command, build command
script:
#  - pytest
  - pyinstaller --onefile --version-file=.travis/version.txt .travis/build.spec

# Deployment code    
deploy:
  provider: releases
  api_key:
    secure: $DEPLOYMENT_KEY_GITHUB
  file_glob: true
  file: dist/*
  skip_cleanup: true
  on:
    tags: true
    TRAVIS_PYTHON_VERSION: "3.6"
